/**
 * Ansible Technical Marketing team directory.
 * Add or update members here — team pages render from this data.
 */
const TEAM = [
  {
    slug: 'andrius-benokraitis',
    name: 'Andrius Benokraitis',
    title: 'Manager, Ansible Technical Marketing',
    location: 'Durham, NC',
    photo: 'andrius-benokraitis.png',
    bio: 'Andrius is a Senior Manager, Technical Marketing for Ansible Automation Platform. He brings over 20 years in the computer software industry from companies such as IBM, Nortel, and Cumulus Networks. Andrius is skilled in Network Automation, Enterprise Linux, Business Analytics, Technical Writing, and Strategic Alliances.',
    funFact: 'Ansible F1 calls him "The Evangelist" — and yes, he once bought 400 pounds of chicken tenders in a single Costco trip because bulk is a lifestyle.',
    linkedin: 'https://www.linkedin.com/in/andriusbeno/',
    redhatAuthorNid: '580001',
    redhat: 'https://www.redhat.com/en/authors/andrius-benokraitis',
    github: 'https://github.com/abenokraitis',
  },
  {
    slug: 'anshul-behl',
    name: 'Anshul Behl',
    username: 'abehl',
    title: 'Principal Technical Marketing Manager — Ansible',
    location: 'Toronto, Canada',
    photo: 'anshul-behl.png',
    bio: 'Anshul is a Principal Marketing Manager at Red Hat, where he brings his software development and QE experience to increase Ansible Automation Platform\'s adoption experience for customers by producing technical content on all aspects of the product.',
    funFact: 'In Ansible F1 he is "The Optimizer" — former neural-net architect, competitive diver, and father of two future engineers.',
    linkedin: 'https://www.linkedin.com/in/ianshulbehl/',
    redhatAuthorNid: '580021',
    redhat: 'https://www.redhat.com/en/authors/anshul-behl',
    github: 'https://github.com/anshulbehl',
    twitter: 'https://x.com/anshul_behl',
  },
  {
    slug: 'alex-walczyk',
    name: 'Alex Walczyk',
    username: 'awalczyk',
    title: 'Technical Marketing Manager',
    location: 'Durham, NC',
    photo: 'alex-walczyk.png',
    bio: 'Alex is a Technical Marketing Manager for Ansible at Red Hat, where he builds demos and technical content that help practitioners adopt automation. He joined the team after internships with Ansible—where he implemented Event Driven Ansible workflows for network security—and at Tesla\'s HPC/AI Infrastructure group, supporting GPU cluster operations for initiatives including FSD and Optimus. A software engineer by training, he brings hands-on development experience to every workshop and customer session.',
    funFact: 'Ansible F1 nicknamed him "The Kid" — youngest on the grid, cracked his first firewall at 12, and his car is yellow so you see him coming.',
    linkedin: 'https://www.linkedin.com/in/alex-walczyk/',
    github: 'https://github.com/abwalczyk',
  },
  {
    slug: 'aubrey-trotter',
    name: 'Aubrey Trotter',
    username: 'atrotter',
    title: 'Technical Marketing Manager',
    location: 'Durham, NC',
    photo: 'aubrey-trotter.png',
    bio:
      'Aubrey is a Technical Marketing Manager for Ansible at Red Hat, focused on automation strategies that improve operational efficiency and system resilience. They create solutions for incident recovery and device self-healing across large-scale network environments.\n\n' +
      'Before Red Hat, Aubrey developed and maintained automation for more than 130,000 network devices globally at Wells Fargo, working with teams across the US and India on troubleshooting, testing, and implementing new solutions while establishing code standards that kept operations scalable. They began their career in software development through the Road to Hire apprenticeship program.',
    funFact: 'Known in Ansible F1 as "The Architect" — once deployed a zero-downtime migration across four continents while making dinosaur chicken nuggets.',
    linkedin: 'https://www.linkedin.com/in/ammtrotter/',
    redhatAuthorNid: '858601',
    redhat: 'https://www.redhat.com/en/authors/aubrey-trotter',
    github: 'https://github.com/amoyament',
  },
  {
    slug: 'sean-cavanaugh',
    name: 'Sean Cavanaugh',
    username: 'scavanau',
    title: 'Senior Principal Technical Marketing Manager — Ansible',
    location: 'Chapel Hill, NC',
    photo: 'sean-cavanaugh.png',
    bio:
      'Sean is a Senior Principal Technical Marketing Manager at Red Hat. He builds the demos, workshops, and educational content that help engineers understand and adopt Ansible Automation Platform.\n\n' +
      'Before Red Hat, he worked at Cumulus Networks and Cisco, where he developed a deep understanding of network infrastructure and the challenges of managing it at scale. That experience shaped his approach: make complex technology accessible through hands-on demonstrations and clear storytelling.\n\n' +
      'He has spoken at over 50 conferences including Red Hat Summit, AnsibleFest, Cisco Live, All Things Open, and AutoCon, from Atlanta to Tokyo to Seoul. His YouTube channel has grown to over 16,000 subscribers.\n\n' +
      'When he\'s not building demos or on stage, he explores how AI agents can transform infrastructure management, and shares what he learns along the way.',
    funFact: 'The Ansible F1 architect! Spent so many tokens creating the game that now we have AI token restrictions. But hey, now we have godzilla and kingkong... try it out!',
    linkedin: 'https://www.linkedin.com/in/seanecavanaugh/',
    redhatAuthorNid: '579961',
    redhat: 'https://www.redhat.com/en/authors/sean-cavanaugh',
    github: 'https://github.com/orgs/ansible-tmm/people/IPvSean',
    twitter: 'https://x.com/IPvSean',
    bluesky: 'https://bsky.app/profile/ipvsean.bsky.social',
  },
  {
    slug: 'hicham-mourad',
    name: 'Hicham Mourad',
    username: 'hmourad',
    title: 'Consulting Technical Marketing Manager — Ansible',
    location: 'Ottawa, Canada',
    photo: 'hicham-mourad.png',
    bio: 'Hicham is responsible for technical marketing of the Red Hat Ansible Automation Platform on Clouds. Hicham has been in the software industry for over 20 years and for many of them focused on cloud management. Hicham has been a frequent presenter at events and conferences like VMworld, vForum, VMUG, VMLive, Gartner, Dell Technology World, AWS re:Invent, HPE Discover, Cloud Field Day, Red Hat Summit, AnsibleFest, in addition to Customer events.',
    funFact: 'Ansible F1 calls him "The Architect of Clouds" — born in Beirut, forged in Ottawa, and fueled by an unreasonable amount of maple syrup.',
    linkedin: 'https://www.linkedin.com/in/hichammourad/',
    redhatAuthorNid: '783991',
    redhat: 'https://www.redhat.com/en/authors/hicham-mourad',
    github: 'https://github.com/HichamMourad',
    twitter: 'https://x.com/HichamMourad',
  },
  {
    slug: 'leonardo-gallego',
    name: 'Leonardo Gallego',
    username: 'lgallego',
    title: 'Senior Technical Marketing Manager — Ansible Community',
    location: 'Buenos Aires, Argentina',
    photo: 'leonardo-gallego.png',
    bio: 'Leonardo is a Senior Technical Marketing Manager at Red Hat. He drives the adoption of Ansible by developing and promoting technical content, including hands-on workshops, meetups and upstream collaboration. He has been an Open Source enthusiast and professional for over 20 years. He is a Red Hat Certified Engineer and Specialist in Advanced Ansible Automation.',
    funFact: 'Ansible F1 knows him as "El Rayo" — wrote his first program at five, better at soccer than Messi (allegedly), and despises broccoli.',
    linkedin: 'https://www.linkedin.com/in/leogallego/',
    redhatAuthorNid: '852361',
    redhat: 'https://www.redhat.com/en/authors/leonardo-gallego',
    github: 'https://github.com/leogallego',
    twitter: 'https://x.com/leogallegored',
  },
  {
    slug: 'nuno-martins',
    name: 'Nuno Martins',
    username: 'nmartins',
    title: 'Senior Principal Technical Marketing Manager',
    location: 'Johannesburg, South Africa',
    photo: 'nuno-martins.png',
    bio: 'Nuno is a Technical Marketing Manager for the Ansible Automation Platform. He is a Red Hat Certified Architect and a Certified Instructor with over 15 years of experience in multiple technologies. Currently based in South Africa, he has international experience with having worked all over Europe and Africa.',
    funFact: 'In Ansible F1, the dark web fears him and the hippos obey him. His pickup truck runs on diesel and paranoia.',
    linkedin: 'https://www.linkedin.com/in/nunomartins9/',
    redhatAuthorNid: '783381',
    redhat: 'https://www.redhat.com/en/authors/nuno-martins',
    github: 'https://github.com/nmartins0611',
    twitter: 'https://x.com/NunoMart11',
  },
  {
    slug: 'roger-lopez',
    name: 'Roger Lopez',
    username: 'rlopez',
    title: 'Senior Principal Technical Marketing Manager',
    location: 'Austin, TX',
    photo: 'roger-lopez.png',
    bio: 'Roger creates Kubernetes, OpenShift, and orchestration demos that show Ansible Automation Platform at scale. A frequent speaker and content creator who makes complex platform stories accessible to technical audiences.',
    funFact: 'Ansible F1 calls him "El Orquestador" — holds the unofficial record for most pods on a single OpenShift cluster, deployed via Ansible during a brisket smoke.',
    linkedin: 'https://www.linkedin.com/in/rogeralopez/',
    redhatAuthorNid: '429931',
    redhat: 'https://www.redhat.com/en/authors/roger-lopez',
    github: 'https://github.com/rlopez133',
    twitter: 'https://x.com/Lopez',
  },
];
